### ISSUE TITLE
blog adblock ASN

### ISSUE THREAD

**Issue by zgzgng** [theel0ja/CrapBlock#6]
I read an "article" a while back about killing the entire third party ad ecosystem by blocking on an ASN level.  You seem like the kind of hacker involved on the adblocking front to stir that pot.

**Comment by zgzgng** [comment]
"the end of third party interweb ads forever"

**Comment by theel0ja** [comment]
You can use a firewall to block all IP blocks announced by an ASN.

Related: https://www.dan.me.uk/bgplookup
